// アプリ初回起動時に登録しておく初期都市一覧
// 「Country」ではなく「Region」表記を使う方針のため、フィールド名もregionName/regionCodeとする
export const INITIAL_CITIES = [
  {
    id: 'tokyo-jp',
    name: 'Tokyo',
    displayName: 'Tokyo',
    regionName: 'Japan',
    regionCode: 'JP',
    flag: '🇯🇵',
    latitude: 35.6762,
    longitude: 139.6503,
    timezone: 'Asia/Tokyo',
    sortOrder: 1,
  },
  {
    id: 'osaka-jp',
    name: 'Osaka',
    displayName: 'Osaka',
    regionName: 'Japan',
    regionCode: 'JP',
    flag: '🇯🇵',
    latitude: 34.6937,
    longitude: 135.5023,
    timezone: 'Asia/Tokyo',
    sortOrder: 2,
  },
  {
    id: 'seoul-kr',
    name: 'Seoul',
    displayName: 'Seoul',
    regionName: 'South Korea',
    regionCode: 'KR',
    flag: '🇰🇷',
    latitude: 37.5665,
    longitude: 126.978,
    timezone: 'Asia/Seoul',
    sortOrder: 3,
  },
  {
    id: 'shanghai-cn',
    name: 'Shanghai',
    displayName: 'Shanghai',
    regionName: 'China',
    regionCode: 'CN',
    flag: '🇨🇳',
    latitude: 31.2304,
    longitude: 121.4737,
    timezone: 'Asia/Shanghai',
    sortOrder: 4,
  },
  {
    id: 'taipei-tw',
    name: 'Taipei',
    displayName: 'Taipei',
    // 台湾は中国とは別のregionとして扱う
    regionName: 'Taiwan',
    regionCode: 'TW',
    flag: '🇹🇼',
    latitude: 25.033,
    longitude: 121.5654,
    timezone: 'Asia/Taipei',
    sortOrder: 5,
  },
  {
    id: 'hongkong-hk',
    name: 'Hong Kong',
    displayName: 'Hong Kong',
    // 香港は中国とは別のregionとして扱う
    regionName: 'Hong Kong',
    regionCode: 'HK',
    flag: '🇭🇰',
    latitude: 22.3193,
    longitude: 114.1694,
    timezone: 'Asia/Hong_Kong',
    sortOrder: 6,
  },
  {
    id: 'newyork-us',
    name: 'New York',
    displayName: 'New York',
    regionName: 'United States',
    regionCode: 'US',
    flag: '🇺🇸',
    latitude: 40.7128,
    longitude: -74.006,
    timezone: 'America/New_York',
    sortOrder: 7,
  },
  {
    id: 'paris-fr',
    name: 'Paris',
    displayName: 'Paris',
    regionName: 'France',
    regionCode: 'FR',
    flag: '🇫🇷',
    latitude: 48.8566,
    longitude: 2.3522,
    timezone: 'Europe/Paris',
    sortOrder: 8,
  },
]
